name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}


    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}

    - name: Install Terminus Build Tools
      run: terminus self:plugin:install terminus-build-tools-plugin

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add pantheon $pantheon_repo
        git add .
        git commit -q -m 'Build assets for dev.'
        git push --force pantheon HEAD:refs/heads/$BASE_BRANCH